# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Andhika Maheva Wicaksono
tagline:             Tulisan Mahasiswa Biasa
url:                 http://andhikamaheva.github.io
paginate:            3
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andhika Maheva Wicaksono
  url:               https://twitter.com/andhikamaheva
  email:             andhikamaheva@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/andhikamaheva/andhikamaheva.github.io
